openapi: 3.0.0
info:
  title: GitHub Helper API
  version: 1.0.0
servers:
  - url: https://github-helper-jet.vercel.app/api/app
paths:
  /user/repos:
    get:
      summary: List repositories for the authenticated user
      operationId: listUserRepos
      responses:
        '200':
          description: A list of repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'

  /repos/{owner}/{repo}/issues:
    post:
      summary: Create a new issue in the specified repository
      operationId: createIssue
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewIssue'
      responses:
        '201':
          description: Created issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'

  /repos/{owner}/{repo}/pulls:
    post:
      summary: Create a new pull request in the specified repository
      operationId: createPullRequest
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPullRequest'
      responses:
        '201':
          description: Created pull request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewPullRequest'
  /repos/{owner}/{repo}/pulls/{pull_number}/reviews:
    post:
      summary: Create a review for the specified pull request
      operationId: createPullRequestReview
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: pull_number
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPullRequestReview'
      responses:
        '200':
          description: Created review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PullRequestReview'
  /repos/{owner}/{repo}/issues/{issue_number}/comments:
    post:
      summary: Create a comment on the specified issue or pull request
      operationId: createComment
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: issue_number
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewComment'
      responses:
        '201':
          description: Created comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'

  /repos/{owner}/{repo}/commits:
    post:
      summary: Create a new commit in the specified repository
      operationId: createCommit
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCommit'
      responses:
        '201':
          description: Created commit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commit'

components:
  schemas:
    Repository:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        full_name:
          type: string
        description:
          type: string

    NewIssue:
      type: object
      properties:
        title:
          type: string
        body:
          type: string
        assignees:
          type: array
          items:
            type: string
        labels:
          type: array
          items:
            type: string

    Issue:
      type: object
      properties:
        id:
          type: integer
        number:
          type: integer
        title:
          type: string
        body:
          type: string
        state:
          type: string
        user:
          $ref: '#/components/schemas/User'
        assignees:
          type: array
          items:
            $ref: '#/components/schemas/User'
        labels:
          type: array
          items:
            $ref: '#/components/schemas/Label'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    NewPullRequestReview:
      type: object
      properties:
        body:
          type: string
        event:
          type: string
          enum: [APPROVE, REQUEST_CHANGES, COMMENT]

    PullRequestReview:
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: '#/components/schemas/User'
        body:
          type: string
        state:
          type: string

    NewComment:
      type: object
      properties:
        body:
          type: string

    Comment:
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: '#/components/schemas/User'
        body:
          type: string

    NewCommit:
      type: object
      properties:
        message:
          type: string
        tree:
          type: string
        parents:
          type: array
          items:
            type: string

    Commit:
      type: object
      properties:
        sha:
          type: string
        message:
          type: string

    User:
      type: object
      properties:
        login:
          type: string
        id:
          type: integer

    NewPullRequest:
      type: object
      properties:
        title:
          type: string
        head:
          type: string
        base:
          type: string
        body:
          type: string
        draft:
          type: boolean
        maintainer_can_modify:
          type: boolean

    Label:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        color:
          type: string


