openapi: 3.0.0
info:
  title: GitHub Helper API
  version: 1.0.0
servers:
  - url: https://github-helper-jet.vercel.app/api/github
paths:
  /list_repos:
    get:
      summary: List repositories for the authenticated user
      operationId: listUserRepos
      responses:
        '200':
          description: A list of repositories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
  /browse_repo/{owner}/{repo}/{path}:
    get:
      summary: Browse a repository's folders and files
      operationId: browseRepo
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: path
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of folders and files in the specified path
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FileOrFolder'
  /create_branch:
    post:
      summary: Create a new branch
      operationId: createBranch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBranch'
      responses:
        '201':
          description: Created branch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Branch'
  /delete_branch:
    delete:
      summary: Delete a branch
      operationId: deleteBranch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BranchToDelete'
      responses:
        '204':
          description: Branch deleted
  /create_commit:
    post:
      summary: Create a new commit
      operationId: createCommit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCommit'
      responses:
        '201':
          description: Created commit
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commit'
  /update_file:
    put:
      summary: Update a file
      operationId: updateFile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFile'
      responses:
        '200':
          description: Updated file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
  /delete_file:
    delete:
      summary: Delete a file
      operationId: deleteFile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteFile'
      responses:
        '204':
          description: File deleted
  /create_pull_request:
    post:
      summary: Create a new pull request
      operationId: createPullRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPullRequest'
      responses:
        '201':
          description: Created pull request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PullRequest'
  /get_pull_request:
    get:
      summary: Get a pull request
      operationId: getPullRequest
      parameters:
        - name: owner
          in: query
          required: true
          schema:
            type: string
        - name: repo
          in: query
          required: true
          schema:
            type: string
        - name: pull_number
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A pull request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PullRequest'
  /review_pull_request:
    post:
      summary: Review a pull request with comments
      operationId: reviewPullRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '201':
          description: Created review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'

components:
  schemas:
    Repository:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        full_name:
          type: string
        private:
          type: boolean
    FileOrFolder:
      type: object
      properties:
        type:
          type: string
          enum: [file, dir]
        name:
          type: string
        path:
          type: string
    NewBranch:
      type: object
      properties:
        owner:
          type: string
        repo:
          type: string
        branch_name:
          type: string
        base_ref:
          type: string
    BranchToDelete:
      type: object
      properties:
        owner:
          type: string
        repo:
          type: string
        branch_name:
          type: string
    Branch:
      type: object
      properties:
        name:
          type: string
        commit:
          $ref: '#/components/schemas/Commit'
    NewCommit:
      type: object
      properties:
        owner:
          type: string
        repo:
          type: string
        message:
          type: string
        tree:
          type: string
        parents:
          type: array
          items:
            type: string
    Commit:
      type: object
      properties:
        sha:
          type: string
        url:
          type: string
        message:
          type: string
    UpdateFile:
      type: object
      properties:
        owner:
          type: string
        repo:
          type: string
        path:
          type: string
        content:
          type: string
    DeleteFile:
      type: object
      properties:
        owner:
          type: string
        repo:
          type: string
        path:
          type: string
    File:
      type: object
      properties:
        sha:
          type: string
        filename:
          type: string
        status:
          type: string
        additions:
          type: integer
        deletions:
          type: integer
        changes:
          type: integer
        blob_url:
          type: string
        raw_url:
          type: string
        content_url:
          type: string
        patch:
          type: string
    NewPullRequest:
      type: object
      properties:
        owner:
          type: string
        repo:
          type: string
        title:
          type: string
        head:
          type: string
        base:
          type: string
    PullRequest:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
        number:
          type: integer
        state:
          type: string
        title:
          type: string
        body:
          type: string
        head:
          $ref: '#/components/schemas/Branch'
        base:
          $ref: '#/components/schemas/Branch'
    Review:
      type: object
      properties:
        owner:
          type: string
        repo:
          type: string
        pull_number:
          type: integer
        commit_id:
          type: string
        body:
          type: string
        event:
          type: string
          enum: [COMMENT, APPROVE, REQUEST_CHANGES, PENDING]
        comments:
          type: array
          items:
            $ref: '#/components/schemas/ReviewComment'
    ReviewComment:
      type: object
      properties:
        path:
          type: string
        position:
          type: integer
        body:
          type: string
